### ISSUE TITLE
I use config EFI but error

### ISSUE THREAD

**Issue by tuyenpb** [awesometic/hackintosh-gigabyte-b760m-aorus-elite#1]
Info hardware machine
1. Mainboard Gigabyte B760M DS3H DDR4
2. VGA Gigabyte Radeon RX 6600 EAGLE 8GB
3. RAM desktop TEAMGROUP ELITE 16GB DDR4 3200MHZ
4. CPU intel Core I5-14500
5. SSD PNY cs1031 500gb m.2 2280 pciE nv -> install window
**6. SSD Crucial P3 500GB NVMe 3D-NAND M.2 PCIe Gen3 x4 CT500P3SSD8 -> USE SETTUP MACOS hackintosh**

Could you modify the config of folder EFI for me please. I use the EFI of you but error when logo apple show -> it reset forever.

You can contact me via email: tuyenlike@gmail.com, please
Many thank you.

**Comment by awesometic** [comment]
Hello,

I'm sorry I couldn't make an EFI folder for your system because every system has its own specific hardware and someone who works on it should have multiple tests to make it works flawlessly.

For a start point you can refer to the other EFI folder that has the same mainboard to yours.

**Comment by awesometic** [comment]
I will close this issue since it is not related to the main subject of this repository. Thank you.
